# Generated by Django 3.1.1 on 2020-11-04 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('name', models.CharField(db_column='Name', max_length=150, primary_key=True, serialize=False)),
                ('gender', models.CharField(db_column='Gender', max_length=5)),
            ],
            options={
                'db_table': 'categories',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Clothing',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('brand_name', models.CharField(db_column='Brand_Name', max_length=255)),
                ('product_name', models.CharField(db_column='Product_Name', max_length=256)),
                ('price', models.IntegerField(db_column='Price')),
                ('gender', models.CharField(db_column='Gender', max_length=5)),
                ('category', models.CharField(db_column='Category', max_length=50)),
            ],
            options={
                'db_table': 'clothing',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=60)),
                ('code', models.CharField(db_column='Code', max_length=7)),
            ],
            options={
                'db_table': 'color',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=5)),
            ],
            options={
                'db_table': 'size',
                'managed': False,
            },
        ),
    ]
